# Generated by Django 3.1.3 on 2021-02-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_entry_format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_receive', models.DateField()),
                ('proposal_no', models.IntegerField()),
                ('customer_name', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('phone_no', models.IntegerField()),
                ('Mode_call', models.CharField(max_length=30)),
                ('done_date', models.DateField()),
                ('Status', models.CharField(max_length=30)),
                ('remarks', models.CharField(max_length=100)),
                ('recording', models.BooleanField(default=False)),
                ('whatsapp_no', models.IntegerField()),
                ('download_recording', models.CharField(default='Download', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Expire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('code', models.CharField(max_length=50)),
                ('schedule', models.BooleanField(default=False)),
            ],
        ),
    ]
