# Generated by Django 3.1.3 on 2021-02-19 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expire',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 19, 18, 26, 56, 336936)),
        ),
    ]
