# Generated by Django 3.1.6 on 2021-02-12 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expire',
            name='schedule',
            field=models.BooleanField(default=False),
        ),
    ]
