# Generated by Django 3.1.3 on 2021-02-19 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0002_auto_20210219_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expire',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
