# Generated by Django 3.1.3 on 2021-02-19 13:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_app', '0004_auto_20210219_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expire',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 19, 18, 45, 34, 216487)),
        ),
    ]
